language: python

# Code for "run this test on ubuntu"
services:
  - xvfb

install: 
 # install requirements through pip install .
#  - pip install -r requirements.txt
 - pip install .
 # This is for running the tests
 - pip install pytest #pytest-cov codecov

script: 
  # run tests TODO: add code coverage information
  - pytest tests #--cov=src
  # - codecov

  # test pip installation
  - python tests/test_importing.py
