language: python

# Code for "run this test on ubuntu"
services:
  - xvfb

install: 
 - pip install -r requirements.txt
 # This is for running the tests
 - pip install pytest #pytest-cov codecov

script: 
  # run tests TODO: add code coverage information
  - pytest #--cov=src
  # - codecov

  # # test pip installation
  # - pip install .
  # - python -c "import stlab"
